name = "serveur-js"
compatibility_date = "2024-09-22"
compatibility_flags = ["nodejs_compat"]

# [vars]
# MY_VAR = "my-variable"

[[kv_namespaces]]
binding = "users"
id = "99efafe969c049a58ce6702888af8cb3"

[[r2_buckets]]
binding = "storage-policarpe"
bucket_name = "storage-policarpe"

[[d1_databases]]
binding = "DB"                                       # i.e. available in your Worker on env.DB     
database_name = "policarpeDB"
database_id = "0a4b2460-fcec-4b0e-a1b6-ea449afde302"
migrations_dir = "prisma/migrations"

[placement]
mode = "smart"

# [ai]
# binding = "AI"
